#TMIS Form Analyzer Settings
#Sun May 03 21:49:37 NOVT 2026
oracle.password=def
oracle.url=jdbc\:oracle\:thin\:@192.168.241.141\:1521/med2dev
oracle.user=dev
output.dir=SQL_info
postgres.password=postgres
postgres.url=jdbc\:postgresql\://192.168.241.137\:5432/med2dev
postgres.user=postgres
project.path=/var/www/t-mis/mis
report.includeJsForms=true
report.includeJsUnitCompositions=true
report.includeSqlContent=false
report.includeTablesViews=true
report.includeViewDetails=true
report.includeViewTables=true
